### Get all
GET http://localhost:3001/api/persons

### Get by ID
GET http://localhost:3001/api/persons/1

### Delete by ID
DELETE http://localhost:3001/api/persons/1

### Create new person
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
	"id": 4,
	"name": "MankaLover69420",
	"number": "13-13-1313420"
}